title: Data for analyzing cannabis strains
description: The core of this dataset is a list of cannabis strains found in cannabis use and education website Leafly in October 2021.

publisher_text:
publisher_url:

license_text:
license_url:

frequency:

certificate_embed:
