title: Data for analyzing cannabis strains
description: A group of datasets meant to facilitate and further the quantitative analysis of cannabis strains (specifically strain naming). Includes information from cannabis use and education website Leafly in October 2021.

publisher_text: N/A
publisher_url: 

license_text: N/A
license_url: 

frequency: N/A

certificate_embed: N/A
