title: Data for analyzing cannabis strains
description: A group of datasets meant to facilitate and further the quantitative analysis of cannabis strain naming. Includes information from cannabis use and education website Leafly in October 2021.

publisher_text:
publisher_url:

license_text:
license_url:

frequency:

certificate_embed:
